In [1]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('/Users/zachkeskinen/Documents/infrasound/data/hwy21-avis/2022.csv', index_col = 0, parse_dates = True)

In [7]:
df

,Location,Size,Type,Trigger,Road_Affected,Road_open
Date,,,,,,
2022-01-10,96.86,1,SS,N,y,n
2022-01-10,96.88,1,SS,N,y,n
2022-01-10,96.92,2,SS,N,y,n
2022-01-10,98.2,1,SS,N,n,n
2022-01-10,98.4,3,SS,N,y,n
2022-01-10,98.5,1,SS,N,n,n
2022-01-10,grand - 98.93,3,SS,N,y,n
2022-01-10,goat - 99.59,1,SS,N,n,n
2022-01-10,99.86 R,2,SS,N,y,n
2022-01-10,travis,2,SS,N,y,n
2022-01-10,99.9,3,SS,N,y,n
2022-01-10,100.04,1,SS,N,y,n
2022-01-10,100.12,1,SS,N,y,n
2022-01-10,100.15,1,SS,N,y,n
2022-01-10,100.2,1,SS,N,y,n
2022-01-10,100.5,1,SS,N,y,n
2022-01-10,kiwi,1,SS,N,n,n
2022-01-10,Enter the Dragon 99.89 R,2,SS,N,n,n
2022-01-10,100.12 R,1,SS,N,n,n
2022-02-11,shoshoni 100.04,1,WL,N,y,y
2022-02-11,six shooter,2,WL,N,n,y
2020-03-02,96.92,2,WL,N,y,y
2020-03-02,hairtrigger,1,WL,N,y,y
2020-03-04,96.86,2,WL,N,y,n
2020-03-04,96.88,2,WL,N,y,n
2020-03-04,hairtrigger,1,WL,N,y,n
2020-03-04,99.9,1,WL,N,y,n
2020-03-04,100.15,1,WL,N,y,n
2020-03-04,100/2,1,WL,N,y,n